name: 'Return an Error Message'
description: 'Return an Error Message'

inputs:
  error-message:
    description: "random"
    default: "error message 1"

runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Send Error
      shell: bash
      run: |
        token='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <RaiseFault async="false" continueOnError="false" enabled="true" name="RFNotInADGroup">
          <DisplayName>RF. NotInADGroup</DisplayName>
          <FaultRules/>
          <Properties/>
          <FaultResponse>
            <Set>
              <Headers/>
              <Payload contentType="text/plain">User is not in the permitted AD groups ({allowedAdGroups}) for this resource. </Payload>
              <StatusCode>403</StatusCode>
              <ReasonPhrase>Forbidden</Reason Phrase>
            </Set>
          </FaultResponse>
          <IgnoreUnresolvedVariables>true</IgnoreUnresolvedVariables>
          <ShortFaultReason>false</ShortFaultReason>
        </RaiseFault>'
        echo "$token" | cut -d"\"" -f4
