name: 'Return an Error Message'
description: 'Return an Error Message'

inputs:
  random-input:
    description: "random"
    default: "1"

runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - if: ${{ inputs.random-input == '1' }}
      name: Send Error
      shell: bash
      run: |
        echo "Error 1" >&2
        exit 1

    - if: ${{ inputs.random-input == '2' }}
      name: Send Error
      shell: bash
      run: |
        echo "Error 2" >&2
        exit 2
