name: 'Return an Error Message'
description: 'Return an Error Message'

inputs:
  error-message:
    description: "random"
    default: "error message 1"

runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Send Error
      shell: bash
      run: |
        echo "echoing error"
        echo "CUSTOM_ERROR=Error the process failed" >> $GITHUB_ENV
        exit 1
